# Setup

In [ ]:
# user setup
import os

# custom Kaggle login (environment variables are recommended)
os.environ["KAGGLE_USERNAME"] = "" or os.getenv("KAGGLE_USERNAME")
os.environ["KAGGLE_KEY"] = "" or os.getenv("KAGGLE_KEY")

# spark configuration
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64" or os.getenv("JAVA_HOME")
os.environ["SPARK_HOME"] = "" or os.getenv("SPARK_HOME")

# subsampling: percentage of commenting users to keep
USERS_PERCENTAGE = 0.1
assert 0 < USERS_PERCENTAGE <= 1, "invalid USER_PERCENTAGE, should be in (0, 1]"

# configuration
MIN_KW_FREQ = 5 # minimum frequency of keywords to be included in the profile (for the dictionary approach)
FEATURES_SIZE = 5000 # number of features, buckets of the hash (for the hashing approach)
LSH_NUM_HASHES = 100 # number of random hyperplanes (signatures/sketches)
LSH_BANDS = 10 # TODO: play with b and r (calculate the threshold for different values)
LSH_ROWS = 10
assert LSH_NUM_HASHES == LSH_BANDS * LSH_ROWS, "invalid LSH_NUM_HASHES, must be equal to LSH_BANDS * LSH_ROWS"

In [ ]:
# setup dataset
%pip install kaggle
!test -d dataset && echo "Skipping dataset download" || (kaggle datasets download -d "benjaminawd/new-york-times-articles-comments-2020" && unzip -d dataset new-york-times-articles-comments-2020.zip && rm -f new-york-times-articles-comments-2020.zip 2> /dev/null)

In [ ]:
# setup spark
!test -d spark && echo "Skipping spark download" || (wget -q https://dlcdn.apache.org/spark/spark-4.1.1/spark-4.1.1-bin-hadoop3.tgz -O spark.tgz && mkdir spark && tar xvf spark.tgz -C spark --strip-components=1 > /dev/null && rm spark.tgz)
%pip install pyspark
%pip install py4j
import pyspark
ss = (pyspark.sql.SparkSession
    .builder
    .getOrCreate())
sc = ss.sparkContext

In [ ]:
csv_options = {
    "header": "true",
    "inferSchema": "true",
    "quote": '"',
    "escape": '"', # quotes " in the dataset are escaped ""
    "multiLine": "true",
    "mode": "PERMISSIVE",
}

full_articles = ss.read.options(**csv_options).csv("dataset/nyt-articles-2020.csv")
full_comments = ss.read.options(**csv_options).csv("dataset/nyt-comments-part0.csv") # TODO: this is a subset of all comments

full_articles.take(1), full_comments.take(1)

([Row(newsdesk='Editorial', section='Opinion', subsection=None, material='Editorial', headline='Protect Veterans From Fraud', abstract='Congress could do much more to protect Americans who have served their country from predatory for-profit colleges.', keywords="['Veterans', 'For-Profit Schools', 'Financial Aid (Education)', 'Frauds and Swindling', 'Colleges and Universities', 'Veterans Affairs Department', 'Federal Trade Commission', 'University of Phoenix', 'Career Education Corporation']", word_count=680, pub_date=datetime.datetime(2020, 1, 1, 0, 18, 54), n_comments=186, uniqueID='nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd')],
 [Row(commentID=104387472, status='approved', commentSequence=104387472, userID=60215558, userDisplayName='magicisnotreal', userLocation='earth', userTitle=None, commentBody='Here is something I think is fraudulent that vets are subject to\n If you use your VA home loan option you have to pay higher interest rates regardless of your credit rating becuase supposedly it is more risky.\nHow exactly is a guaranteed loan more risky than a not guaranteed commercial loan?', createDate=datetime.datetime(2020, 1, 1, 1, 5, 46), updateDate=datetime.datetime(2020, 1, 1, 8, 13, 39), approveDate=datetime.datetime(2020, 1, 1, 1, 5, 47), recommendations=7, replyCount=5, editorsSelection=False, parentID=None, parentUserDisplayName=None, depth=1, commentType='comment', trusted=0, recommendedFlag=0, permID=104387472, isAnonymous=False, articleID='nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd')])

In [ ]:
%pip install mmh3 # non-cryptographic hash, better distribution
# utility hash function: bytes | str -> signed int 32
def h(data):
    import mmh3
    return mmh3.hash(data)

In [ ]:
# parse keywords column utility
def parse_keywords(row):
    import re
    if not row["keywords"]: return []
    kws = re.sub(r'\[|\]|\'|\"', '', row["keywords"].lower()).strip()
    if not kws: return []
    return [w.strip() for w in kws.split(",") if len(w.strip()) > 0]

# keep only relevant information for recommendations porpouse, convert from dataframe to RDD tuples
articles = (full_articles
            .select("uniqueID", "newsdesk", "section", "subsection", "keywords")
            .rdd
            .map(lambda row: (row["uniqueID"], row["newsdesk"], row["section"], row["subsection"], parse_keywords(row))))
comments = (full_comments
            .select("articleID", "userID")
            .rdd
            .map(lambda row: (row["articleID"], row["userID"])))

articles.take(1), comments.take(1)

([('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd',
   'Editorial',
   'Opinion',
   None,
   ['veterans',
    'for-profit schools',
    'financial aid (education)',
    'frauds and swindling',
    'colleges and universities',
    'veterans affairs department',
    'federal trade commission',
    'university of phoenix',
    'career education corporation'])],
 [('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 60215558)])

## Utility Matrix

In [ ]:
utility_matrix = comments.distinct() # TODO: keep multiple comments on same article or not?
utility_matrix.take(5), utility_matrix.count()

([('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 60215558),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 65691034),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 65110053),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 66232009),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 73299044)],
 356283)

## Articles Profile - via dictionary

In [ ]:
# count frequencies
keywords = (articles
            .flatMap(lambda row: [(k, 1) for k in row[4]])
            .reduceByKey(lambda a, b: a + b))

# prune too rare keywords
pruned_keywords = (keywords
                   .filter(lambda x: x[1] >= MIN_KW_FREQ and len(x[0]) <= 100)
                   .map(lambda x: f"KEY {x[0]}")
                   .collect())

# extract all features
features = sorted(pruned_keywords + (articles
            .flatMap(lambda row: [f"{f} {row[i+1].lower().strip()}" for i, f in enumerate(["NEW", "SEC", "SUB"]) if row[i+1]])
            .filter(lambda x: len(x) < 100)
            .distinct()
            .collect()))

# features mapping dictionary, needs to be broadcasted to every node
features_mapping = {f: i for i, f in enumerate(features)}
print(f"Extacted {len(features_mapping)} features (broadcasting at most {((100 * 4) + 4) * len(features_mapping) // 1024} KB)")
broadcast_dict = sc.broadcast(features_mapping)

# build sparse vectors for profiles (article_id, feature_index)
def build_article_profile_dict(row):
    mapping = broadcast_dict.value
    res = []
    for i, f in enumerate(["NEW", "SEC", "SUB"]):
        if not row[i+1]: continue
        f = f"{f} {row[i+1].lower().strip()}"
        if f not in mapping: continue
        res.append((row[0], mapping[f]))
    for k in row[4]:
        k = f"KEY {k.lower().strip()}"
        if k not in mapping: continue
        res.append((row[0], mapping[k]))
    return res

articles_profile_dict = articles.flatMap(build_article_profile_dict)
articles_profile_dict.take(10), articles_profile_dict.count()

Extacted 3555 features (broadcasting at most 1402 KB)

([('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 3395),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 3465),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 3193),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 1131),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 1097),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 1158),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 628),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 3194),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 1086),
  ('nyt://article/9edddb54-0aa3-5835-a833-d311a76f1e7c', 3399)],
 158079)

## Articles Profile - via hashing

In [ ]:
# build sparse vectors for profiles (article_id, feature_hash)
def build_article_profile_hash(row):
    res = []
    for i, f in enumerate(["NEW", "SEC", "SUB"]):
        if not row[i+1]: continue
        f = f"{f} {row[i+1].lower().strip()}"
        res.append((row[0], h(f) % FEATURES_SIZE))
    for k in row[4]:
        k = f"KEY {k.lower().strip()}"
        res.append((row[0], h(k) % FEATURES_SIZE))
    return res

articles_profile_hash = articles.flatMap(build_article_profile_hash)
articles_profile_hash.take(10), articles_profile_hash.count()

([('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 653),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 2704),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 2692),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 1483),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 4497),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 260),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 1675),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 2683),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 3196),
  ('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd', 598)],
 185396)

### WARNING

From now on, the operations will be **independent** of how the profiles were computed (via dictionary or hashing).
Change the content of next cell to change approach: (`articles_profile_dict` or `articles_profile_hash`)

In [ ]:
articles_profile = articles_profile_hash

## Users Profile

In [ ]:
# build user profiles by joining utility matrix with article profiles, then counting feature frequencies for each user
users_profile = (utility_matrix
                     .join(articles_profile)
                     .map(lambda x: ((x[1][0], x[1][1]), 1))
                     .reduceByKey(lambda a, b: a + b))
users_profile.take(10), users_profile.count()

([((5646097, 535), 36),
  ((5646097, 2881), 36),
  ((5646097, 4221), 36),
  ((86273619, 535), 11),
  ((86273619, 2881), 11),
  ((86273619, 4221), 11),
  ((61536727, 535), 9),
  ((61536727, 2881), 9),
  ((61536727, 4221), 9),
  ((41508509, 535), 20)],
 2801463)

## Computing Similarity - LSH using hyperplanes (sketches)

In [25]:
import random

# random vectors of +1 and -1 of dimensione FEATURES_SIZE
random_hyperplanes = [[random.choice([-1, 1]) for _ in range(FEATURES_SIZE)] for _ in range(LSH_NUM_HASHES)]
b_hyperplanes = sc.broadcast(random_hyperplanes)

def compute_sketch(row):
    item_id, sparse_features = row
    sketch = []
    for plane in b_hyperplanes.value:
        # dot product: if above or below the hyperplane
        # only considering the features that exist in the sparse vector
        dot_product = sum(weight * plane[feat] for feat, weight in sparse_features)
        # 1 if positive, 0 if negative
        sketch.append(1 if dot_product > 0 else 0)
    return (item_id, sketch)

# compute sketches ("equivalent" of signature) for users and articles
users_sketches = (users_profile
                  .map(lambda x: (x[0][0], ((x[0][1], x[1]))))
                  .groupByKey()
                  .mapValues(list)
                  .map(compute_sketch))
articles_sketches = (articles_profile
                  .map(lambda x: (x[0], ((x[1], 1))))
                  .groupByKey()
                  .mapValues(list)
                  .map(compute_sketch))

users_sketches.take(1), articles_sketches.take(1)

([(13120442,
   [1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    1,
    0,
    0,
    1,
    1,
    0,
    0,
    1,
    0,
    0,
    1,
    0,
    1,
    1,
    1,
    0,
    1,
    0,
    0,
    1,
    1,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    0,
    0,
    1,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    1,
    1,
    0,
    0,
    1,
    0,
    0,
    0])],
 [('nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd',
   [1,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    0,
    1,
    1,
    1,
    0,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    0,
    0,
    0,
    1,
    1,
    0,
    0,
    1,
    0,
    1,
    1,
    0,
    0,
    0,
    0,
    1,
    1,
    0,
    1,
    1,
    1,
    0,
    1,
    1,
    0,
    1,
    1,
    1,
    0,
    1,
    0,
    1,
    1,
    1,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    0,
    0,
    1,
    0,
    0,
    0,
    1,
    1,
    0,
    1,
    0,
    0,
    1,
    1,
    0,
    0,
    0,
    0,
    1,
    0,
    1,
    1,
    1,
    0,
    0,
    0,
    0])])

In [26]:
def lsh_buckets(row, what):
    item_id, sketch = row
    res = []
    for band in range(LSH_BANDS):
        band_signature = tuple(sketch[band*LSH_ROWS : (band+1)*LSH_ROWS])
        bucket_hash = h(f"b{band}_{band_signature}") # include band index to avoid collisions between different bands
        res.append((bucket_hash, (what, item_id)))
    return res

users_buckets = users_sketches.flatMap(lambda x: lsh_buckets(x, "USER"))
articles_buckets = articles_sketches.flatMap(lambda x: lsh_buckets(x, "ARTICLE"))

users_buckets.take(10), articles_buckets.take(10)

([(-1528755988, ('USER', 13120442)),
  (573874805, ('USER', 13120442)),
  (109712757, ('USER', 13120442)),
  (456923391, ('USER', 13120442)),
  (-686120117, ('USER', 13120442)),
  (-2031674836, ('USER', 13120442)),
  (1117070857, ('USER', 13120442)),
  (765610745, ('USER', 13120442)),
  (464771685, ('USER', 13120442)),
  (-961146683, ('USER', 13120442))],
 [(1272973056,
   ('ARTICLE', 'nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd')),
  (1941486667,
   ('ARTICLE', 'nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd')),
  (1521742613,
   ('ARTICLE', 'nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd')),
  (1725585274,
   ('ARTICLE', 'nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd')),
  (1266562358,
   ('ARTICLE', 'nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd')),
  (-1947116141,
   ('ARTICLE', 'nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd')),
  (764242108,
   ('ARTICLE', 'nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd')),
  (928440656,
   ('ARTICLE', 'nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd')),
  (-1098407110,
   ('ARTICLE', 'nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd')),
  (-834389377,
   ('ARTICLE', 'nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd'))])

In [ ]:
# no distinct 20 bands x 5 rows = ~1b results in 3min 20s
# no distinct 10 bands x 10 rows = ~50m results in 30s
#    distinct 10 bands x 10 rows = ~30m results in 6min 50s

recommendations = (users_buckets
                   .join(articles_buckets)
                   .map(lambda x: (x[1][0][1], x[1][1][1])))
                   # TODO: distinct and subtrack make sense but are really really slow and use a loooot of memory
                   # right now the distinct and subtraction are done per-user in the actual recommendation step, but it would be better to do them here
                   # .distinct()
                   # .subtract(utility_matrix))

recommendations.take(10), recommendations.count()

([(13120442, 'nyt://article/7a227b82-431e-5bc5-a0c0-7d9581e89cc8'),
  (13120442, 'nyt://article/f9183d03-2495-5377-a396-d0efbdfbf764'),
  (13120442, 'nyt://article/2e747dcd-f037-53e5-a219-a2bec2b77003'),
  (13120442, 'nyt://article/63ebfdab-87ee-5d8d-87bd-3e4a44325ec3'),
  (13120442, 'nyt://article/75e15e35-7d18-57fa-80ab-64e1926fdbd2'),
  (13120442, 'nyt://article/65cff85d-1be4-5453-87f8-07049b4d2514'),
  (13120442, 'nyt://article/ca5694f3-c121-53e3-9a35-1f429f23daa8'),
  (13120442, 'nyt://article/b1249e4c-5ead-54d6-b076-cb4c009159b4'),
  (13120442, 'nyt://article/34be1c27-d0a7-50d7-bf8e-1fe3925351b7'),
  (13120442, 'nyt://article/b55374dc-5333-52c3-a6bb-cbe48d44298c')],
 59044038)

In [43]:
USER_ID = 13120442 # 0.24054 over 377 recommendations ['top 5: 0.5834', 'top 10: 0.56436', 'top 20: 0.54242']
# USER_ID = 86273619 # 0.61674 over 454 recommendations ['top 5: 0.98126', 'top 10: 0.98126', 'top 20: 0.98126']
# USER_ID = 61536727 # 0.61831 over 457 recommendations ['top 5: 0.98198', 'top 10: 0.98198', 'top 20: 0.98198']
# USER_ID = 79217680 # 0.03767 over 178 recommendations ['top 5: 0.6175', 'top 10: 0.47482', 'top 20: 0.32519']
# USER_ID = 77701784 # 0.12554 over 355 recommendations ['top 5: 0.48529', 'top 10: 0.44943', 'top 20: 0.38532']

# cosine similarity between sparse profiles, user_profile and article_profile should be dicts {feature_index: weight}
def cosine_similarity(user_profile, article_profile):
    dot_product = sum(user_profile.get(feat, 0) * weight for feat, weight in article_profile.items())
    user_norm = sum(weight ** 2 for weight in user_profile.values()) ** 0.5
    article_norm = sum(weight ** 2 for weight in article_profile.values()) ** 0.5
    if user_norm == 0 or article_norm == 0:
        return 0.0
    return dot_product / (user_norm * article_norm)

# single user recommendations with article profile
user_reccs = (recommendations
            .filter(lambda x: x[0] == USER_ID)
            # TODO: next two steps should be done above in the recommendations RDD
            .distinct()
            .subtract(utility_matrix.filter(lambda x: x[1] == USER_ID).map(lambda x: (x[1], x[0]))) # remove already commented articles
            .map(lambda x: (x[1], None)) # without a valid pair, the join will not return anything
            .join(articles_profile.map(lambda x: (x[0], (x[1], 1))).groupByKey().mapValues(list))
            .map(lambda x: (x[0], x[1][1])))

user_profile = dict(users_profile
                    .filter(lambda x: x[0][0] == USER_ID)
                    .map(lambda x: (x[0][1], x[1]))
                    .collect())

similarities = []
for article, profile in user_reccs.collect():
    sim = cosine_similarity(user_profile, dict(profile))
    similarities.append(round(sim, 5))
    # print(article, sim)

similarities.sort(reverse=True)
print(f"Average similarity: {(sum(similarities) / len(similarities)):.5f} over {len(similarities)} recommendations {[('top ' + str(qty) + ': ' + str(round(sum(similarities[:qty]) / qty, 5))) for qty in [5, 10, 20]]}")

Average similarity: 0.24506 over 384 recommendations ['top 5: 0.60967', 'top 10: 0.58667', 'top 20: 0.56074']

---
---

In [44]:
# setup pandas (tests before scaling to spark)
%pip install pandas
import pandas as pd
articles = pd.read_csv("dataset/nyt-articles-2020.csv")
comments = pd.read_csv("dataset/nyt-comments-part0.csv") # TODO: this is already a sample
print(f"Dataset size: {len(articles)=}, {len(comments)=}")
(articles.columns, comments.columns)

Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/lib/python3.11/site-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Dataset size: len(articles)=16787, len(comments)=500000

(Index(['newsdesk', 'section', 'subsection', 'material', 'headline', 'abstract',
        'keywords', 'word_count', 'pub_date', 'n_comments', 'uniqueID'],
       dtype='object'),
 Index(['commentID', 'status', 'commentSequence', 'userID', 'userDisplayName',
        'userLocation', 'userTitle', 'commentBody', 'createDate', 'updateDate',
        'approveDate', 'recommendations', 'replyCount', 'editorsSelection',
        'parentID', 'parentUserDisplayName', 'depth', 'commentType', 'trusted',
        'recommendedFlag', 'permID', 'isAnonymous', 'articleID'],
       dtype='object'))

In [45]:
# subsampling
# WARNING: executing this cell multiple times without executing previous cell will continue to shrink the dataset
if USERS_PERCENTAGE < 1:
    total_users = len(comments['userID'].unique())
    subsampled_users = int(total_users * USERS_PERCENTAGE)
    top_users = comments['userID'].value_counts().nlargest(subsampled_users).index # keep top users
    print(top_users) # TODO

    print(f"Subsampling from {total_users} to {subsampled_users} users:")

    print(f"- comments: {len(comments)} -> ", end="")
    comments = comments[comments['userID'].isin(top_users)].copy() # keep only comments from these users
    print(f"{len(comments)}")

    active_article_ids = comments['articleID'].unique() # keep only commented articles
    print(f"- articles: {len(articles)} -> ", end="")
    articles = articles[articles['uniqueID'].isin(active_article_ids)].copy() # keep only commented articles
    print(f"{len(articles)}")

Index([ 67892453,  68938663,  73444633,  33668404,  69498476,  78358680,
        63483890,  72967915,  87081404,  93082167,
       ...
        49632588,     61360,  80245071,  22822988,  28571829,  21227474,
        65684325, 103084739,  78118899,  42471841],
      dtype='int64', name='userID', length=9143)
Subsampling from 91437 to 9143 users:
- comments: 500000 -> 313145
- articles: 16787 -> 1593

# Utility Matrix

In [46]:
utility_matrix = pd.crosstab(index=comments['userID'], columns=comments['articleID'])
utility_matrix = (utility_matrix > 0).astype(int) # ignore multiple comments on the same article
utility_matrix

articleID,nyt://article/00036db7-8494-5141-b0ac-414118caabee,nyt://article/00168469-d42e-5a6f-9c81-90e3306c6c85,nyt://article/004716c5-8943-5bf4-8293-864ab083d676,nyt://article/00573cb4-92bb-53b7-ad9a-6d4d1e734704,nyt://article/00bea7d5-c04a-509d-a82f-7537a16dfeb1,nyt://article/012aeb93-8149-522b-a18b-d6cfc620fb22,nyt://article/016cf3b3-56e9-53e4-882c-549209211afb,nyt://article/0178a7cd-b6b8-58b2-afe4-3d1f68aef248,nyt://article/01a433cd-37ce-5e77-a39b-fe4af162a34f,nyt://article/01b7c5aa-9cf5-56a0-8162-3b8d606ce533,...,nyt://interactive/c46aa52e-ec78-5e20-8145-acaa9d1d5705,nyt://interactive/c696fd2f-2287-562e-91ec-3f07747a9923,nyt://interactive/c6ec5381-c3f8-5a71-b23a-a0d9b18c7237,nyt://interactive/c891ed57-1184-52d9-bd9c-cf9f7bf23f13,nyt://interactive/d0598a7b-06ba-56db-9df4-7a2afa1c95e3,nyt://interactive/dcc11686-2ae2-562c-9e2b-738e9140b9d4,nyt://interactive/df6cd908-52b0-5851-ac81-e7b8039d50d1,nyt://interactive/e31c6ca3-4bea-5a56-b358-7986e7590f1d,nyt://interactive/e5bd1257-4e08-5656-bc03-091a2597e336,nyt://interactive/f91ad36a-9e5c-5e95-a210-37f1b797fdf3
userID,,,,,,,,,,,,,,,,,,,,,
2593,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8010,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8638,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13323,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
17282,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109551783,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109587542,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109738098,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109837657,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109978040,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Content-Based Recommendations

### Articles Profile

In [47]:
# items profile
feature_columns = ["newsdesk", "section", "subsection"]
item_features_matrix = pd.get_dummies(articles[feature_columns], dtype=int)
item_features_matrix.index = articles['uniqueID'].values
# articles["profile"] = item_features_matrix.values.tolist()
item_features_matrix

,newsdesk_Arts,newsdesk_Arts&Leisure,newsdesk_BookReview,newsdesk_Books,newsdesk_Business,newsdesk_Climate,newsdesk_Culture,newsdesk_Dining,newsdesk_Editorial,newsdesk_Express,...,subsection_Pro Football,subsection_Self-Care,subsection_Skiing,subsection_Soccer,subsection_Sunday Review,subsection_Television,subsection_Tennis,subsection_The Daily,subsection_Weddings,"subsection_Wine, Beer & Cocktails"
nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
nyt://article/9edddb54-0aa3-5835-a833-d311a76f1e7c,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
nyt://article/04bc90f0-b20b-511c-b5bb-3ce13194163f,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
nyt://article/bd8647b3-8ec6-50aa-95cf-2b81ed12d2dd,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
nyt://article/ac742403-9ccd-522f-9a1e-a90feb6c0acd,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
nyt://article/b9c293a0-dfb4-5630-9948-8a39be8afce8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
nyt://article/203dd447-5d08-5745-95b8-b97de174d4b9,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
nyt://article/1e2029bd-8b3d-5e1e-9e78-28e5ff746998,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
nyt://article/697c75a8-2600-5e81-98ac-38193d89ae12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
nyt://article/49cedd40-d966-5fa1-a04a-1db9abc2756a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Users Profile

In [48]:
# user profile: count how many times each user commented on articles with each label
user_profiles = []

for user_id in utility_matrix.index:
    commented_articles = utility_matrix.loc[user_id][utility_matrix.loc[user_id] == 1].index # articles commented by this user
    user_profile = item_features_matrix.loc[item_features_matrix.index.isin(commented_articles)].sum(axis=0) # sum features vectors for these articles
    user_profiles.append(user_profile)

user_features_matrix = pd.DataFrame(user_profiles, index=utility_matrix.index)
user_features_matrix

,newsdesk_Arts,newsdesk_Arts&Leisure,newsdesk_BookReview,newsdesk_Books,newsdesk_Business,newsdesk_Climate,newsdesk_Culture,newsdesk_Dining,newsdesk_Editorial,newsdesk_Express,...,subsection_Pro Football,subsection_Self-Care,subsection_Skiing,subsection_Soccer,subsection_Sunday Review,subsection_Television,subsection_Tennis,subsection_The Daily,subsection_Weddings,"subsection_Wine, Beer & Cocktails"
userID,,,,,,,,,,,,,,,,,,,,,
2593,0,0,0,0,2,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8010,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8638,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
13323,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
17282,0,2,0,0,3,0,1,0,2,0,...,2,0,0,0,3,2,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109551783,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109587542,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109738098,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109837657,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109978040,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Calculate Recommendations

In [49]:
from sklearn.metrics.pairwise import cosine_similarity # TODO: implement from scratch?
similarity_array = cosine_similarity(user_features_matrix, item_features_matrix)
similarity_df = pd.DataFrame(
    similarity_array,
    index=user_features_matrix.index,
    columns=item_features_matrix.index
)
similarity_df.to_csv("similarity_df.csv")
similarity_df

,nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd,nyt://article/9edddb54-0aa3-5835-a833-d311a76f1e7c,nyt://article/04bc90f0-b20b-511c-b5bb-3ce13194163f,nyt://article/bd8647b3-8ec6-50aa-95cf-2b81ed12d2dd,nyt://article/ac742403-9ccd-522f-9a1e-a90feb6c0acd,nyt://article/dea10063-7440-586f-bc32-db1dbaa9893f,nyt://article/dfd5bb59-f330-5c01-ae02-221e6f9cae7a,nyt://article/6227c991-6a3d-5eb1-92c9-a618f6e20dbd,nyt://article/7d9a4f78-44ef-5756-bc2b-4c13cbfa0d5a,nyt://article/da74e3b3-f027-5b03-9052-0bc2e69a2f3e,...,nyt://article/23ec0066-2831-599d-bbff-cef34498ab07,nyt://article/2ae8b3b1-f038-5953-a83a-8b75389010da,nyt://article/67b90b5b-fbb1-5f4b-ab12-7fcc24793bcf,nyt://article/d118dda5-b976-56f9-81c7-a961dcff8e84,nyt://article/46182ac4-985b-5b2d-9c4c-5ca4c9552fdd,nyt://article/b9c293a0-dfb4-5630-9948-8a39be8afce8,nyt://article/203dd447-5d08-5745-95b8-b97de174d4b9,nyt://article/1e2029bd-8b3d-5e1e-9e78-28e5ff746998,nyt://article/697c75a8-2600-5e81-98ac-38193d89ae12,nyt://article/49cedd40-d966-5fa1-a04a-1db9abc2756a
userID,,,,,,,,,,,,,,,,,,,,,
2593,0.185341,0.0,0.030890,0.030890,0.680985,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.000000,0.226995,0.370681,0.370681,0.000000,0.000000,0.302660,0.403547
8010,0.046424,0.0,0.000000,0.000000,0.000000,0.278543,0.278543,0.278543,0.000000,0.000000,...,0.00000,0.0,0.000000,0.644383,0.092848,0.092848,0.000000,0.000000,0.075810,0.947623
8638,0.396059,0.0,0.099015,0.099015,0.080845,0.000000,0.000000,0.000000,0.099015,0.161690,...,0.19803,0.0,0.099015,0.242536,0.693103,0.693103,0.000000,0.000000,0.565916,0.161690
13323,0.553519,0.0,0.000000,0.000000,0.150649,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.000000,0.075324,0.968658,0.968658,0.000000,0.000000,0.790906,0.150649
17282,0.552536,0.0,0.000000,0.000000,0.000000,0.157867,0.157867,0.157867,0.039467,0.000000,...,0.00000,0.0,0.118401,0.193347,0.868271,0.868271,0.128898,0.193347,0.805614,0.128898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109551783,0.000000,0.0,0.250000,0.250000,0.408248,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
109587542,0.267261,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.145479,...,0.00000,0.0,0.000000,0.727393,0.534522,0.534522,0.000000,0.000000,0.436436,0.727393
109738098,0.500000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.816497,0.000000
109837657,0.426401,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.000000,0.348155,0.852803,0.852803,0.000000,0.000000,0.696311,0.522233
109978040,0.000000,0.0,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [50]:
articles_lookup = articles.set_index("uniqueID", drop=False)

def print_article(i, article_id, score=None):
    if article_id in articles_lookup.index:
        row = articles_lookup.loc[article_id]
        title = row.get("headline", row.get("title", "N/A"))
        abstract = row.get("abstract", "N/A")
        newsdesk = row.get("newsdesk", "N/A")
        section = row.get("section", "N/A")
        subsection = row.get("subsection", "N/A")
    else:
        title = abstract = newsdesk = section = subsection = "N/A"

    score_str = f" | score: {score:.5f}" if score is not None else ""
    print(f"{i}. article_id: {article_id}{score_str} | {title} | {abstract} | {newsdesk=} | {section=} | {subsection=}")

def print_results(user_id, recommendations=5):

    commented_ids = []
    if user_id in utility_matrix.index:
        commented = utility_matrix.loc[user_id]
        commented_ids = commented[commented > 0].index.tolist()

    scores = similarity_df.loc[user_id].sort_values(ascending=False)
    # remove alreayd commented articles
    scores = scores.drop(index=commented_ids, errors="ignore")


    print(f"=== Top {len(scores.head(recommendations))} recommendations for user {user_id}:")
    for i, (article_id, score) in enumerate(scores.head(recommendations).items(), start=1):
        print_article(i, article_id, score)

    print(f"\n=== Articles already commented by user {user_id} ({len(commented_ids)}):")
    for i, article_id in enumerate(commented_ids, start=1):
        print_article(i, article_id)

print_results(similarity_df.index[12], 50)

=== Top 50 recommendations for user 42569:
1. article_id: nyt://article/8a86511a-17d6-55e1-aa07-7866cd8ef600 | score: 0.75000 | Trump Acts Like a Politician. That’s Not an Impeachable Offense. | Receiving a “political benefit” does not transform an otherwise legal action (like requesting an investigation) into an abuse of power. | newsdesk='OpEd' | section='Opinion' | subsection=nan
2. article_id: nyt://article/9279bb5d-2909-5a7e-a986-4c962749b224 | score: 0.75000 | An Open Letter to John Lewis | As you fight a new battle, we owe you a debt of gratitude for being a moral compass for our nation. | newsdesk='OpEd' | section='Opinion' | subsection=nan
3. article_id: nyt://article/2d63ffca-75d3-5e97-b794-42cc57fa377b | score: 0.75000 | Trump Has a Bizarre Idea of Winning | Let’s tally up the results of his efforts with Iran. | newsdesk='OpEd' | section='Opinion' | subsection=nan
4. article_id: nyt://article/17e3f286-50bc-5127-af57-164567d1a380 | score: 0.75000 | The Many Polarizations of America | Three new books cover the different ways and reasons that we’ve ended up divided. | newsdesk='OpEd' | section='Opinion' | subsection=nan
5. article_id: nyt://article/fdf55793-554c-55bd-9439-ac1ffcfb0ae5 | score: 0.75000 | Bernie Could Win the Nomination. Should We Be Afraid? | The establishment doesn’t have the credibility to stop the surging Sanders movement. | newsdesk='OpEd' | section='Opinion' | subsection=nan
6. article_id: nyt://article/68111fb7-b006-580a-b3ae-35d7601a748d | score: 0.75000 | Did Trump and Iran Just Bury the Hatchet, or the Future? | They can each claim some victory. But what did they win? | newsdesk='OpEd' | section='Opinion' | subsection=nan
7. article_id: nyt://article/f468c618-93ca-57bc-80d2-dad705dbb0ef | score: 0.75000 | Why the W.N.B.A. Loved Kobe Bryant | His skills proved that basketball is a mental game. Plus, he was a fan. | newsdesk='OpEd' | section='Opinion' | subsection=nan
8. article_id: nyt://article/5cce3595-30c7-55a1-ad1c-adae5f7b9b36 | score: 0.75000 | Trump Hurts an Ally and Helps the Terrorists | The administration has sacrificed a crucial relationship with Iraq at the altar of a dangerous policy on Iran. | newsdesk='OpEd' | section='Opinion' | subsection=nan
9. article_id: nyt://article/5e6a2ce8-32e5-5b44-a853-2874f53254ed | score: 0.75000 | Some Wins for the Women | Just block Donald Trump out of your mind. | newsdesk='OpEd' | section='Opinion' | subsection=nan
10. article_id: nyt://article/647352cd-4101-537e-a639-ba0e2d316c87 | score: 0.75000 | Greta Versus the Greedy Grifters | Why a 17-year-old is a better economist than Steve Mnuchin. | newsdesk='OpEd' | section='Opinion' | subsection=nan
11. article_id: nyt://article/a13cc7a2-5b58-5e3d-9914-1fb4352c2339 | score: 0.75000 | To Beat Trump, Put Ideals Before Ideas | Voters in this presidential election are more concerned with the candidates’ values than their proposals. | newsdesk='OpEd' | section='Opinion' | subsection=nan
12. article_id: nyt://article/85bcd531-c576-5822-abf5-cbd000952678 | score: 0.75000 | A Democrat Who Can Beat Trump | Why Amy Klobuchar still has a chance. | newsdesk='OpEd' | section='Opinion' | subsection=nan
13. article_id: nyt://article/2e813ca4-4391-501a-b45a-2817ee3b79cc | score: 0.75000 | Crisis as Political Catalyst | The Democratic presidential candidate must be able to respond to any situation. | newsdesk='OpEd' | section='Opinion' | subsection=nan
14. article_id: nyt://article/a2c6f327-440f-5573-8e59-5273c8022ed7 | score: 0.75000 | ‘The View’ Has a Meghan McCain Problem | The daytime co-hosts’ heated bipartisan debates are played down as disagreement among friends. But the strain for “civility” is tiring. | newsdesk='OpEd' | section='Opinion' | subsection=nan
15. article_id: nyt://article/898c0560-3712-5e77-8ebf-3f7f251a1652 | score: 0.75000 | This Question Is More Important Than Removing Trump | Can a sitting president block witnesses at his own impeachment trial? | newsdesk='OpEd' | section='Opinion' | subsection=nan
16. article_id: nyt://article/5c12f624-6028-5ed7-b6b9-320b4da9b5ad | score: 0.75000 | John Roberts Can Call Witnesses to Trump’s Trial. Will He? | Democratic House managers should ask the chief justice to issue subpoenas for John Bolton and others. | newsdesk='OpEd' | section='Opinion' | subsection=nan
17. article_id: nyt://article/3dd2bb22-3800-56b2-ae8c-7bdad6726969 | score: 0.75000 | Who Will Be Left Standing in the Supreme Court? | The Trump administration is doing its best to kick plaintiffs out of lawsuits it opposes. | newsdesk='OpEd' | section='Opinion' | subsection=nan
18. article_id: nyt://article/00573cb4-92bb-53b7-ad9a-6d4d1e734704 | score: 0.75000 | Vladimir Putin’s New Orchestra | The players are being rearranged, but the conductor remains the same. | newsdesk='OpEd' | section='Opinion' | subsection=nan
19. article_id: nyt://article/c8f4e6a4-1cd3-50b0-859c-8b287e04702b | score: 0.75000 | ‘How Much Did Killing Suleimani Cost Us?’ | Readers react to the heightened tensions between the United States and Iran. | newsdesk='OpEd' | section='Opinion' | subsection=nan
20. article_id: nyt://article/2b8f75d6-514b-5677-9d27-2d9d30c14850 | score: 0.75000 | Yes, Secretary Pompeo, Americans Should Care About Ukraine | A former ambassador tells the secretary of state just why. | newsdesk='OpEd' | section='Opinion' | subsection=nan
21. article_id: nyt://article/af69007e-6f1f-56f4-a2ce-07a5b608bc66 | score: 0.75000 | Iowa Should Never Go First Again | The current system is a form of white privilege that warps the process. | newsdesk='OpEd' | section='Opinion' | subsection=nan
22. article_id: nyt://article/40ead710-5f13-537a-bfd2-5836bb8ed5ce | score: 0.75000 | How Democrats Can Win Back Obama-Trump Defectors | They don’t have to lose their souls to do it. Just the opposite. | newsdesk='OpEd' | section='Opinion' | subsection=nan
23. article_id: nyt://article/5a01182c-8a7d-5b91-8991-dc7573b2da21 | score: 0.75000 | The Anti-Israel Craze Hits High School | A movement to demonize Israel corrupts the academy. | newsdesk='OpEd' | section='Opinion' | subsection=nan
24. article_id: nyt://article/6eb1a4e7-a85e-50c4-a797-695b33b8eec6 | score: 0.75000 | Reporters Face New Threats From the Governments They Cover | The cases against Julian Assange and Glenn Greenwald may be models for a crackdown. | newsdesk='OpEd' | section='Opinion' | subsection=nan
25. article_id: nyt://article/141d4fc1-4e71-5148-8943-fb7938abe710 | score: 0.75000 | Why Are Young Americans Killing Themselves? | Suicide is now their second-leading cause of death. | newsdesk='OpEd' | section='Opinion' | subsection=nan
26. article_id: nyt://article/d2a137d8-d456-5ecf-8a4b-99f9ea4f60d1 | score: 0.75000 | The Long Battle With Iran | Qassim Suleimani’s death brought vindication for the many American lives he took over the years. But what comes next? | newsdesk='OpEd' | section='Opinion' | subsection=nan
27. article_id: nyt://article/217df12a-4fee-5760-9cc5-127a40c61898 | score: 0.75000 | Latin America’s Radical Feminism Is Spreading | Women in Chile, Brazil, Argentina and elsewhere know: Stopping violence against women starts with politics and power. | newsdesk='OpEd' | section='Opinion' | subsection=nan
28. article_id: nyt://article/dc908804-0dad-5419-9cfa-95c91180e3a0 | score: 0.75000 | Mitch McConnell’s Complicity Has Deep Roots | With or without witnesses, Trump’s trial shows that the antifederalists were right to question the Senate’s purpose. | newsdesk='OpEd' | section='Opinion' | subsection=nan
29. article_id: nyt://article/c4320133-81a1-5bc2-9d13-5c12af783f83 | score: 0.75000 | How Much of Harvard’s $40 Billion Endowment Is Invested in Fossil Fuels? | It’s not all that important. Any amount is too much. | newsdesk='OpEd' | section='Opinion' | subsection=nan
30. article_id: nyt://article/643e59e1-a307-5b55-b28b-2245bc156a5a | score: 0.75000 | Why Having Hunter Biden Testify Would Be Bad for Trump | If it means John Bolton would also testify in the impeachment trial, it could help the Democrats. | newsdesk='OpEd' | section='Opinion' | subsection=nan
31. article_id: nyt://article/539d7732-eddf-55a9-b391-701494e01abe | score: 0.75000 | You Are Unvaccinated and Got Sick. These Are Your Odds. | Comparing the dangerous effects of three diseases with the minimal side effects of their corresponding vaccines. | newsdesk='OpEd' | section='Opinion' | subsection=nan
32. article_id: nyt://article/3c1fafa8-5c3b-5a18-b44b-14c51f94a8a1 | score: 0.75000 | Coronavirus Spreads, and the World Pays for China’s Dictatorship | Xi used his tight rule to control information rather than to stop an epidemic. | newsdesk='OpEd' | section='Opinion' | subsection=nan
33. article_id: nyt://article/86b99f9a-1bd5-5a8a-a320-2836d21fafac | score: 0.75000 | What Will You Do When the Culture War Comes for You? | Newsrooms still aren’t ready for the trolls. | newsdesk='OpEd' | section='Opinion' | subsection=nan
34. article_id: nyt://article/3a474a55-d2e6-5fd0-84e8-79cf04571120 | score: 0.75000 | Tech Loses a Prophet. Just When It Needs One. | Clay Christensen’s bracing ideas about management are more relevant than ever as the tech industry seeks redemption. | newsdesk='OpEd' | section='Opinion' | subsection=nan
35. article_id: nyt://article/d4b0af48-3593-5010-802d-c1b1069c8f15 | score: 0.75000 | Beware the Pandemic Panic | Coronavirus is scary. How we respond to it may be worse. | newsdesk='OpEd' | section='Opinion' | subsection=nan
36. article_id: nyt://article/6b64441e-617c-59ce-a760-ca5746500a48 | score: 0.75000 | Women May Finally Be Declared Equal | If the Virginia legislature votes to ratify the Equal Rights Amendment, it may become law. | newsdesk='OpEd' | section='Opinion' | subsection=nan
37. article_id: nyt://article/118137eb-e5bd-5c94-81c3-62216c106962 | score: 0.75000 | Trump Kills Iran’s Most Overrated Warrior | Suleimani pushed his country to build an empire, but drove it into the ground instead. | newsdesk='OpEd' | section='Opinion' | subsection=nan
38. article_id: nyt://article/96810498-f4b7-5b2b-8539-cf6fdcc4473c | score: 0.75000 | Trump’s Digital Advantage Is Freaking Out Democratic Strategists | Left and right agree on one point. The president’s re-election campaign is way ahead online. | newsdesk='OpEd' | section='Opinion' | subsection=nan
39. article_id: nyt://article/66b47457-c921-5632-ab45-26f99e82de0c | score: 0.75000 | How the Iowa Caucuses Work | A little bit of choice, a whole lot of chaos. | newsdesk='OpEd' | section='Opinion' | subsection=nan
40. article_id: nyt://article/b6ce563c-a5d9-5c79-85cb-2360205a1b92 | score: 0.75000 | President Mitch McConnell | He’s in charge of everything but shooting at Iran. | newsdesk='OpEd' | section='Opinion' | subsection=nan
41. article_id: nyt://article/b30b9a81-fd13-50ec-823d-15290fd9b4ff | score: 0.75000 | Warren and Klobuchar Teach the Boys a Lesson | At the Democratic debate, gender comes to the fore. | newsdesk='OpEd' | section='Opinion' | subsection=nan
42. article_id: nyt://article/e9ff04f8-b93a-597a-a6ce-4e7dc5d364fc | score: 0.75000 | Pompeo Called Me a ‘Liar.’ That’s Not What Bothers Me. | Journalists are supposed to ask tough questions, then share the answers — or lack thereof — with the world. | newsdesk='OpEd' | section='Opinion' | subsection=nan
43. article_id: nyt://article/9a5e808c-2ab4-553f-b5a2-62ee1ea036cb | score: 0.75000 | My Journey to Radical Environmentalism | It’s never too late to take action aimed at protecting our planet. | newsdesk='OpEd' | section='Opinion' | subsection=nan
44. article_id: nyt://article/d90bc8c6-cddc-5f9b-b038-6f33f9ed6345 | score: 0.75000 | John Bolton Gets the Last Laugh | He’s the president’s bane and impeachment’s star. | newsdesk='OpEd' | section='Opinion' | subsection=nan
45. article_id: nyt://article/7bb2e857-d2d5-5616-a615-caeb7146bafd | score: 0.75000 | The Dire Consequences of Trump’s Suleimani Decision | One thing is clear after the killing of Iran’s second most important official: Americans are not safer. | newsdesk='OpEd' | section='Opinion' | subsection=nan
46. article_id: nyt://article/1b791986-26f8-502b-902f-d9a66ddab641 | score: 0.75000 | Should You Be Worried About the Coronavirus? | Public health experts explain the risks and what we still don’t know. | newsdesk='OpEd' | section='Opinion' | subsection=nan
47. article_id: nyt://article/1b4939f6-85b4-585b-bf09-0f414d90dbad | score: 0.75000 | Weaponizing Truth Against Opioids | A decades-old campaign that knew how to talk to teenagers persuaded millions of them to never start smoking. Can it now persuade them never to misuse opioids? | newsdesk='OpEd' | section='Opinion' | subsection=nan
48. article_id: nyt://article/30164768-c1e4-5554-9bbd-46d624431e10 | score: 0.75000 | The Groundbreaking Artist Who’s Not Slowing Down at 93 | In the first film from our Sundance 2020 series, meet Betye Saar, who says her weapon is art. | newsdesk='OpEd' | section='Opinion' | subsection=nan
49. article_id: nyt://article/e038497e-e593-522e-b3b0-0007c90cf8cb | score: 0.75000 | The American-Iranian Psychosis, Next Chapter | The mullahs are cold calculators. | newsdesk='OpEd' | section='Opinion' | subsection=nan
50. article_id: nyt://article/6e4c03e2-171b-5bb4-adfc-1257eefdab35 | score: 0.75000 | Harvey Weinstein Is Monster of the Moment, but the Whole System Is Rigged | Demands for sexual pay-to-play by a rutting producer holding all the career cards may be horrific. But it’s not exactly a departure. | newsdesk='OpEd' | section='Opinion' | subsection=nan

=== Articles already commented by user 42569 (16):
1. article_id: nyt://article/1404f827-2357-54af-a20a-3e169333611c | Mayor Pete’s Gay Reckoning | Win or lose in Iowa, Buttigieg has challenged and changed America. | newsdesk='OpEd' | section='Opinion' | subsection='Sunday Review'
2. article_id: nyt://article/1f3779e3-1c93-5037-bbbf-ed3810c5fa58 | Bolton Was Concerned That Trump Did Favors for Autocratic Leaders, Book Says | The former national security adviser shared his unease with the attorney general, who cited his own worries about the president’s conversations with the leaders of Turkey and China. | newsdesk='Washington' | section='U.S.' | subsection='Politics'
3. article_id: nyt://article/22be24e7-b140-5997-a025-2f34e4ddc6fa | Suleimani Died as He Had Killed | Now the United States must establish a balance of hope and fear in the Middle East. | newsdesk='OpEd' | section='Opinion' | subsection=nan
4. article_id: nyt://article/29403e66-ef96-540d-ba8c-e7b8611fce58 | Moo Shu, Now With Less Meat | Faced with a glut of mushrooms, J. Kenji López-Alt added them to a classic Joyce Chen recipe. The result? Tasty, and alliterative. | newsdesk='Dining' | section='Food' | subsection=nan
5. article_id: nyt://article/3299b19f-940f-5b9f-a79a-f4a31b46748e | She’s Harvey Weinstein’s Lawyer, and She Thinks #MeToo Is ‘Dangerous’ | “We can’t have movements that strip us of our fundamental rights,” said Donna Rotunno, who has faced criticism from feminists. | newsdesk='Metro' | section='New York' | subsection=nan
6. article_id: nyt://article/34fad2b7-e7fe-513a-9c8d-6a05a54e106e | Denying a Professor Tenure, Harvard Sparks a Debate Over Ethnic Studies | Some students of color say that even as the university defends its use of race in admissions, it devalues their experiences and fails to retain professors who support them. | newsdesk='National' | section='U.S.' | subsection=nan
7. article_id: nyt://article/60e29555-43de-5c73-9aa2-ecc32401f5a0 | In Era of Perpetual Conflict, a Volatile President Grabs Expanded Powers to Make War | The killing of Maj. Gen. Qassim Suleimani is the latest example of the capricious way in which the president, as commander in chief, has chosen to flex his lethal powers. | newsdesk='Washington' | section='World' | subsection='Americas'
8. article_id: nyt://article/7251704a-3e31-59d6-82cb-b3f8e01a121c | Shelter From Life’s Storms | For the writer Dan Avery, crossword puzzles provide a comforting shield from the painful parts of life. | newsdesk='Games' | section='Crosswords & Games' | subsection=nan
9. article_id: nyt://article/76cb4aa3-1757-5d72-a9f1-c4fedbb730eb | Tropical Breezes, Pristine Beaches and a Domain Name to Die For | Start-ups want unusual internet addresses to help stand out. One winner: The island of Anguilla, whose “.ai” domain is a favorite of A.I. start-ups. | newsdesk='Business' | section='Business Day' | subsection=nan
10. article_id: nyt://article/80bb11e0-cdd2-547e-ab8a-d3e61f10b336 | Pentagon Rules Out Striking Iranian Cultural Sites, Contradicting Trump | The defense secretary acknowledged that “the laws of armed conflict” prohibited attacking antiquities and said the military had no plans to do so, even though the president declared them targets. | newsdesk='Washington' | section='U.S.' | subsection='Politics'
11. article_id: nyt://article/8c5da820-fea9-572f-9bc1-278d053f50d2 | How Does President Sanders Sound to You? | Bernie is surging and may have found his moment. | newsdesk='OpEd' | section='Opinion' | subsection=nan
12. article_id: nyt://article/9779200f-75d2-5db2-a6d2-82655fe272e0 | Waiting Years for This Night, Then Hours for an Iowa Winner | How a day that was supposed to bring clarity to the 2020 race turned into a cliffhanger caucus. | newsdesk='Politics' | section='U.S.' | subsection='Politics'
13. article_id: nyt://article/9edddb54-0aa3-5835-a833-d311a76f1e7c | ‘It’s Green and Slimy’ | Christina Iverson and Jeff Chen ring in the New Year. | newsdesk='Games' | section='Crosswords & Games' | subsection=nan
14. article_id: nyt://article/a12e77d3-38fe-5acb-a3a4-0c49f468cad3 | Everyone Knows Memory Fails as You Age. But Everyone Is Wrong. | Even 20-year-olds forget the simplest things. | newsdesk='OpEd' | section='Opinion' | subsection='Sunday Review'
15. article_id: nyt://article/e71f6f06-66f4-5994-ae67-ca399629e4c5 | The Trump We Did Not Want to See | When are we going to stop trying to rationalize the irrational? | newsdesk='OpEd' | section='Opinion' | subsection=nan
16. article_id: nyt://article/f736ad46-4a4a-5edb-b095-3b9c22742879 | Always Look on the Bright Side of Impeachment | Not to mention the Democratic presidential race. It can be done, if you put your mind to it. | newsdesk='OpEd' | section='Opinion' | subsection=nan